name = "gleastsq"
version = "0.5.2"
target = "erlang"

licences = ["Apache-2.0"]
description = "A least squares curve fitting library for Gleam."
repository = { type = "github", user = "lucaspellegrinelli", repo = "gleastsq" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_otp = ">= 0.10.0 and < 1.0.0"
nx = ">= 0.7.2 and < 1.0.0"
gleam_community_maths = ">= 1.1.1 and < 2.0.0"
exception = ">= 2.0.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
prng = ">= 3.0.3 and < 4.0.0"
